{% set version = "1.1.0" %}

package:
  name: pngpack-py
  version: {{ version }}

source:
  url: https://github.com/axiom-data-science/pngpack/archive/v{{ version }}.zip
  sha256: 2acf96fea9acab5c34a7e70c2d5001cc1d56a5f63873db040958b9bbec6d8fda

build:
  number: 3
  skip: true  # [py<35 or win]
  script: cd pngpack-py && {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libpng
    - python
    - cython
    - pip
  run:
    - libpng
    - python

test:
  imports:
    - pngpack

about:
  home: https://github.com/axiom-data-science/pngpack
  summary: "Python 3 library to pack floating point values into 16-bit PNG images"
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwilcox
