travis:
  secure:
    BINSTAR_TOKEN: c11nWozOFG2+RMSCpcnUWdYHWJikPdYx4j35c84A9igkXjrDBkfYIwqdqQRKJCoQ6nggST4Gy+rOSh1Blg3WOwSfBWIw4OHjETMk5G6bdHW/gl/TXXxjO0FpuEDJVHsTYEe7cAHqZPs0BqXrUPZ4phNZJ/VfTIkoXoVsCLAiuEt6nhm3r0ZH9es/3bggICVFes8tSRxGtE/1vmnyObrDQ3bV5jlmTjTxGHIW+K2sUMMMoEjVMOKizGxniNd8yvclCaWJQEfhMOC946boQ7v1Z8xQZb1oxfp12JFvHuGY96Y9ezNHcNm7zNu8nQfQvR9ay5qh6vrHYzHMomxKkyzwukI53qmFkfTiUUsGTvlDatVnE0Ei+RCNRrvZMPBL7snSfvmwZXHUOpXf5ehXcktzb8Z1KVU/4DWrIaXdDR2xQ+PGv4n4Okg1Din6OkLAIi3JxA+3zwZiOtM7ecTEHbC5rRIcRcYosPrsecLWDVdUKveBl4rp4yaFcTwYj7IMus9DHXX1rVlEjVcdzQFiWNgPy53ScrZyhQV5Bb0pD5REkKhIcKCXzEQ/uBQFHG8rUAVkVJ974TDZ4aHJhVPYq+Vk1YAoLSDNUdKLET2Tz/jYn5nqcTbVnntiVjqVgcF9vU0jioQoKO0Gsf4wKrZ93v6jfmVujfXHv1WFM5EQsi8GI5U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
